name: "Pre-translate in Crowdin"
description: "Pre-translates strings in Crowdin using Translation Memory (TM) and Machine Translation (MT) methods."

inputs:
  crowdinApiToken:
    description: "Crowdin API Token"
    required: true
    type: string
  crowdinBranch:
    description: "Crowdin branch"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Crowdin CLI
      run: npm i -g @crowdin/cli

    - name: Pre-translate with TM
      env:
        CROWDIN_API_TOKEN: ${{ inputs.crowdinApiToken }}
      run: |
        crowdin pre-translate \
          -b "${{ inputs.crowdinBranch }}" \
          --method "tm" \
          --translate-untranslated-only \
          --no-duplicate-translations \
          --auto-approve-option "perfect-match-only" \
          --plain

    - name: Pre-translate with MT
      env:
        CROWDIN_API_TOKEN: ${{ inputs.crowdinApiToken }}
      run: |
        crowdin pre-translate \
          -b "${{ inputs.crowdinBranch }}" \
          --method "mt" \
          --engine-id "535087" \
          --plain
